FROM python:3.8-buster

WORKDIR /app

COPY api/ ./api
COPY es_helpers ./es_helpers
COPY services ./services
COPY app.py ./
COPY .env ./
COPY requirements.txt ./

RUN pip install -r requirements.txt

ENV FLASK_APP "app.py"
EXPOSE 5000
ENTRYPOINT python -m flask run --host=0.0.0.0